version: '3'

services:
  app:
    image: test-typescript-app
    container_name: test-typescript-app
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "80:80"
    tty: true
    volumes:
      - .:/opt/app
  db-mysql:
    container_name: "db-mysql"
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}       # 作成するデータベース名
      MYSQL_USER: ${MYSQL_USER}               # 作業ユーザー名→上記データベースの捜査権限をもつ
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}       # 作業ユーザーのパスワード
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "Asia/Tokyo"
